package sistemabiometrico;

import sistemabiometrico.SistemaBiometrico;
import javax.swing.JFrame;
import sistemabiometrico.UsuarioDAO;
import javax.swing.table.*;
import java.util.ArrayList;
import java.util.List;
public class MenuAdministrador extends javax.swing.JFrame {
    DefaultTableModel modelo;
 
    public MenuAdministrador() {
        initComponents();
        this.setTitle("Adminitrativo");
        this.setLocationRelativeTo(this);
        this.setResizable(false);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbCategoria = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblaPersonas = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 190, 30));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel1.setText("Nombre Y Apellido");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 140, -1));
        jPanel1.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 210, 30));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel2.setText("Identificación (DNI-DI)");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 150, -1));

        cbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celeccione la Categoria", "Estudiante", "Docente", "Obrero", "Administrativo", "Visitantes" }));
        jPanel1.add(cbCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 180, 30));

        jButton1.setText("Guardar");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 90, 100, -1));

        jButton2.setText("Limpiar Formulario");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel3.setText("Penel- Administrativo");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 240, -1));

        tblaPersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Identificación", "Categoria"
            }
        ));
        jScrollPane2.setViewportView(tblaPersonas);

        jScrollPane1.setViewportView(jScrollPane2);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 1020, 450));

        jPanel3.add(jPanel1, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Registro", jPanel3);

        jPanel4.setLayout(new java.awt.BorderLayout());
        jTabbedPane1.addTab("Gestión de Usuario", jPanel4);
        jTabbedPane1.addTab("Reportes", jPanel5);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed


// Acción del botón Guardar

    UsuarioDAO dao = new UsuarioDAO();
    
    // Llamamos a la lógica DAO pasando los datos de la interfaz
    if(dao.registrarPersona (txtNombre.getText(), txtID.getText(), cbCategoria.getSelectedItem().toString())) {
        // Confirmación visual para el administrador
        javax.swing.JOptionPane.showMessageDialog(this, "¡Usuario registrado con éxito!");
        
        // Limpiamos los campos para dejar la pantalla lista para el siguiente registro
        limpiarCampos(); 
    } else {
        // Alerta en caso de problemas con la base de datos
        javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar en base de datos");
    }
}

// Acción del botón Limpiar (Reutilizable para limpiar la pantalla)
private void limpiarCampos() {
    txtNombre.setText("");          // Borra el contenido del campo nombre
    txtID.setText("");              // Borra el contenido del campo ID
    cbCategoria.setSelectedIndex(0); // Regresa el ComboBox a la primera opción
     txtNombre.requestFocus();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(() -> {
            new MenuAdministrador().setVisible(true);
        });
        }
public void cargarTabla() {
  modelo = (DefaultTableModel) tblaPersonas.getModel(); 
    modelo.setRowCount(0); // Limpia la tabla
    
    UsuarioDAO dao = new UsuarioDAO();
    List<Personas> personas = dao.ListarPersona();
    
    for (Personas p : personas) {
        modelo.addRow(new Object[]{p.getNombre(), p.getIdentificacion(), p.getCategoria()});
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbCategoria;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblaPersonas;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
