/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanajframe;
  
/**
 *
 * @author DELL
 */
public class Calculadora extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Calculadora.class.getName());

    
    double primerNumero= 0;//cualda el primernumero antes de hacer la operacion
    String operacion= "";//guarda el boton que se preciono para hacer la operacion
    boolean nuevaEntrada= true;//nos dice si debemos borrar el 0 de la pantalla al escribirl un numero nuevo
    
          
    public Calculadora() {
        initComponents();
           
       this.setTitle("Desarrollado por : ORTIZ");
    this.setLocationRelativeTo(null);    
      this.setResizable(false);  
   }
    public void agregarNumero(String numero) {
        if (nuevaEntrada) {
            txtPantalla.setText("");
            nuevaEntrada = false;
        }
        txtPantalla.setText(txtPantalla.getText() + numero);
    }
     
    // Este método prepara la calculadora para la operación matemática
public void guardarOperacion(String signo) {
    // 1. Convertimos el texto de la pantalla a un número con decimales y lo guardamos
    primerNumero = Double.parseDouble(txtPantalla.getText());
    
    // 2. Guardamos qué operación se quiere hacer (+, -, *, /)
    operacion = signo;
    
    // 3. Avisamos que el siguiente número que se escriba debe limpiar la pantalla
    nuevaEntrada = true;
    
      primerNumero = Double.parseDouble(txtPantalla.getText());
    operacion = signo;
    nuevaEntrada = true;
    
    // 👇 ESTA LÍNEA ES NUEVA: Muestra el primer número y el signo arriba (Ej: "5 x ")
    txtHistorial.setText(txtPantalla.getText() + " " + signo + " ");

     
} 
   
   
   
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel = new javax.swing.JPanel();
        btn0 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnDivicion = new javax.swing.JButton();
        btnMultipica = new javax.swing.JButton();
        btnsuma = new javax.swing.JButton();
        btnresta = new javax.swing.JButton();
        btnpunto = new javax.swing.JButton();
        txtPantalla = new javax.swing.JTextField();
        igual = new javax.swing.JButton();
        txtHistorial = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 204), 1, true));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn0.setText("0");
        btn0.setMaximumSize(new java.awt.Dimension(60, 60));
        btn0.setMinimumSize(new java.awt.Dimension(60, 60));
        btn0.setPreferredSize(new java.awt.Dimension(60, 60));
        btn0.addActionListener(this::btn0ActionPerformed);
        panel.add(btn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 40, 30));

        btn1.setText("1");
        btn1.setMaximumSize(new java.awt.Dimension(23, 23));
        btn1.setMinimumSize(new java.awt.Dimension(23, 23));
        btn1.setPreferredSize(new java.awt.Dimension(55, 55));
        btn1.addActionListener(this::btn1ActionPerformed);
        panel.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 40, 30));

        btn2.setText("2");
        btn2.addActionListener(this::btn2ActionPerformed);
        panel.add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 40, 30));

        btn3.setText("3");
        btn3.addActionListener(this::btn3ActionPerformed);
        panel.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 40, 30));

        btn4.setText("4");
        btn4.addActionListener(this::btn4ActionPerformed);
        panel.add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 40, 30));

        btn5.setText("5");
        btn5.addActionListener(this::btn5ActionPerformed);
        panel.add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 40, 30));

        btn6.setText("6");
        btn6.addActionListener(this::btn6ActionPerformed);
        panel.add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 40, 30));

        btn7.setText("7");
        btn7.addActionListener(this::btn7ActionPerformed);
        panel.add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 40, 30));

        btn8.setText("8");
        btn8.addActionListener(this::btn8ActionPerformed);
        panel.add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 40, 30));

        btn9.setText("9");
        btn9.addActionListener(this::btn9ActionPerformed);
        panel.add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 40, 30));

        btnDivicion.setText("/");
        btnDivicion.addActionListener(this::btnDivicionActionPerformed);
        panel.add(btnDivicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 40, 30));

        btnMultipica.setText("x");
        btnMultipica.addActionListener(this::btnMultipicaActionPerformed);
        panel.add(btnMultipica, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 40, 30));

        btnsuma.setText("+");
        btnsuma.addActionListener(this::btnsumaActionPerformed);
        panel.add(btnsuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 40, 30));

        btnresta.setText("-");
        btnresta.addActionListener(this::btnrestaActionPerformed);
        panel.add(btnresta, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 40, 30));

        btnpunto.setText(".");
        btnpunto.addActionListener(this::btnpuntoActionPerformed);
        panel.add(btnpunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 40, 30));

        txtPantalla.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtPantalla.addActionListener(this::txtPantallaActionPerformed);
        panel.add(txtPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 180, 50));

        igual.setText("=");
        igual.addActionListener(this::igualActionPerformed);
        panel.add(igual, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 40, 30));

        txtHistorial.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        panel.add(txtHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 110, 30));

        btnClear.setText("CLR");
        btnClear.setBorder(null);
        btnClear.addActionListener(this::btnClearActionPerformed);
        panel.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 60, 30));

        jPanel1.add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 230, 330));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
agregarNumero("8");        // TODO add your handling code here:
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
agregarNumero("5");        // TODO add your handling code here:
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
agregarNumero("1");        // TODO add your handling code here:
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
agregarNumero("0");        // TODO add your handling code here:
    }//GEN-LAST:event_btn0ActionPerformed

    private void txtPantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPantallaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPantallaActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
agregarNumero("2");        // TODO add your handling code here:
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
agregarNumero("3");        // TODO add your handling code here:
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
agregarNumero("4");        // TODO add your handling code here:
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
agregarNumero("6");        // TODO add your handling code here:
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
agregarNumero("7");        // TODO add your handling code here:
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
agregarNumero("9");        // TODO add your handling code here:
    }//GEN-LAST:event_btn9ActionPerformed

    private void btnpuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpuntoActionPerformed
      
if (!txtPantalla.getText().contains(".")) {
    agregarNumero(".");
}
    }//GEN-LAST:event_btnpuntoActionPerformed

    private void btnDivicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivicionActionPerformed
guardarOperacion("/");        // TODO add your handling code here:
    }//GEN-LAST:event_btnDivicionActionPerformed

    private void btnMultipicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultipicaActionPerformed
guardarOperacion("*");        // TODO add your handling code here:
    }//GEN-LAST:event_btnMultipicaActionPerformed

    private void btnsumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsumaActionPerformed
guardarOperacion("+");        // TODO add your handling code here:
    }//GEN-LAST:event_btnsumaActionPerformed

    private void btnrestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrestaActionPerformed
guardarOperacion("-");        // TODO add your handling code here:
    }//GEN-LAST:event_btnrestaActionPerformed

    private void igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_igualActionPerformed
double segundoNumero = Double.parseDouble(txtPantalla.getText());
    double resultado = 0;
    
    switch(operacion) {
        case "+":
            resultado = primerNumero + segundoNumero;
            break;
        case "-":
            resultado = primerNumero - segundoNumero;
            break;
        case "*":
            resultado = primerNumero * segundoNumero;
            break;
        case "/":
            if (segundoNumero != 0) {
                resultado = primerNumero / segundoNumero;
            } else {
                txtPantalla.setText("Error");
                nuevaEntrada = true;
                return;
            }
            break;
    }
    
    txtHistorial.setText(txtHistorial.getText() + txtPantalla.getText());
    
    txtPantalla.setText(String.valueOf(resultado));
    nuevaEntrada = true;        // TODO add your handling code here:
    }//GEN-LAST:event_igualActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
txtPantalla.setText("0");
    txtHistorial.setText(""); // Borra también el historial de arriba
    primerNumero = 0;
    operacion = "";
    nuevaEntrada = true;        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Calculadora().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDivicion;
    private javax.swing.JButton btnMultipica;
    private javax.swing.JButton btnpunto;
    private javax.swing.JButton btnresta;
    private javax.swing.JButton btnsuma;
    private javax.swing.JButton igual;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel txtHistorial;
    private javax.swing.JTextField txtPantalla;
    // End of variables declaration//GEN-END:variables
}
