/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_final;

/**
 *
 * @author DELL
 */
import javax.swing.*;
import javax.swing.table.*;
public class Proyecto_Final4 extends javax.swing.JFrame {
    //paso 1
    DefaultTableModel modelo;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Proyecto_Final4.class.getName());

    /**
     * Creates new form Proyecto_Final4
     */
    public Proyecto_Final4() {
        initComponents();
        
        this.setTitle("Evaluativo final - Algoritmos");
        this.setLocationRelativeTo(this);
        this.setResizable(false);
       //paso 2 
     modelo= (DefaultTableModel) TablaPromedios.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        numero1 = new javax.swing.JTextField();
        numero2 = new javax.swing.JTextField();
        numero3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaPromedios = new javax.swing.JTable();
        valorNumero = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        mostrar = new javax.swing.JLabel();
        btnVerificar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnAccionar = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        btnEvento = new javax.swing.JButton();
        btnActivar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txtcantidaRepetir = new javax.swing.JTextField();
        btnContar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        boton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel1.setText("EVALUATIVO FINAL DE ALGORITMO - DISEÑO DE VENTANA CON JFRAME FORME FORM");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 630, 30));
        jPanel1.add(numero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 130, -1));

        numero2.addActionListener(this::numero2ActionPerformed);
        jPanel1.add(numero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 130, -1));

        numero3.addActionListener(this::numero3ActionPerformed);
        jPanel1.add(numero3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 150, -1));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel2.setText("Valor 1");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel3.setText("Valor 2");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, -1, 20));

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel4.setText("Valor 3");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, -1, -1));

        TablaPromedios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número 1", "Número 2", "Número  3", "Promedio"
            }
        ));
        jScrollPane1.setViewportView(TablaPromedios);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 870, 50));
        jPanel1.add(valorNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 210, 30));

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel6.setText("Ingrese el valor númerico");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 220, -1));

        mostrar.setBackground(new java.awt.Color(204, 255, 255));
        mostrar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        mostrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel1.add(mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 330, 40));

        btnVerificar.setText("Verificar");
        btnVerificar.addActionListener(this::btnVerificarActionPerformed);
        jPanel1.add(btnVerificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 110, 30));

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel7.setText("Arreglos estáticos");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel8.setText("Arreglo dinámico");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 220, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel9.setText("Menú");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, 50, 20));

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel10.setText("Calcular Valor");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 280, -1, -1));

        btnAccionar.setText("Accionar");
        btnAccionar.addActionListener(this::btnAccionarActionPerformed);
        jPanel1.add(btnAccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 80, -1));

        btnMostrar.setText("Mostrar menú");
        btnMostrar.addActionListener(this::btnMostrarActionPerformed);
        jPanel1.add(btnMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, -1, -1));

        btnEvento.setText("Evento");
        btnEvento.addActionListener(this::btnEventoActionPerformed);
        jPanel1.add(btnEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 240, 90, -1));

        btnActivar.setText("Activar");
        btnActivar.addActionListener(this::btnActivarActionPerformed);
        jPanel1.add(btnActivar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 300, 100, -1));

        jLabel11.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel11.setText("Ingrese su nombre aqui");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel12.setText("Ingrese la cantidad a repetir");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, -1, -1));
        jPanel1.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 190, -1));
        jPanel1.add(txtcantidaRepetir, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, 180, -1));

        btnContar.setText("Contar");
        btnContar.addActionListener(this::btnContarActionPerformed);
        jPanel1.add(btnContar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 410, 100, -1));

        jLabel13.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel13.setText("Informática- Universidad Bolivariana de Venezuela");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 480, 420, -1));

        jLabel14.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel14.setText("Estudiante: Yilibeth Ortiz - Derechos reservados 2026");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 510, 450, -1));

        boton.setText("calcular promedio");
        boton.addActionListener(this::botonActionPerformed);
        jPanel1.add(boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 90, 140, -1));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numero2ActionPerformed

    private void numero3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numero3ActionPerformed

    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed

        //Ejercicio 2. Par o Impar
     
String entrada = valorNumero.getText();


if (entrada == "") {
    JOptionPane.showMessageDialog(null, "Debe llenar el campo");
} else {
    
    int numero = Integer.parseInt(entrada);
    
    if (numero % 2 == 0) {
        mostrar.setText("El valor ingresado es PAR");
    } else {
        mostrar.setText("El valor ingresado es IMPAR");
    }
    valorNumero.setText("");
    valorNumero.requestFocus();
}
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerificarActionPerformed

    private void btnAccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccionarActionPerformed

        
        
        

String[] componentes = {"Disco duro", "Tarjeta madre", "Memoria RAM", "Teclado", 
    "Cornetas", "Microprocesador", "Monitor", "Mouse", "SSD", "Impresora", "HDD",
    "Placa base", "Tarjeta de red"};


for (int i = 1; i < componentes.length; i++) {
    
   
    JOptionPane.showMessageDialog(null, "Elemento " + i + ": " + componentes[i-1]);
}
      
        
        
        
        
        
        
        
        
        
        
        
        
        
        
      /*  
        //Ejercicio 3. Descripción de Hardware 
        
        String[] hardware = {"Disco duro", "Targeta madre", "Memoria Ram", "Teclado", "Cornetas", "Microprocesador " 
               +"", "Monitor", "Mouse", "Almacenamiento SSD", "Impresora", "Almacenamiento HDD", "Placa base", "Tarjeta de red"};

        JOptionPane.showMessageDialog(null,"Mostrar 12 descripción de hardware usando arreglo.");
        
        for(int i=1; i<hardware.length; i++){
             JOptionPane.showMessageDialog(null,"Elemento " + i +"= " + hardware[i]);
        }
      */
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAccionarActionPerformed

    private void btnEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEventoActionPerformed

        //Ejercicio 4. Arreglo dinamico

      
String pedirTamano = JOptionPane.showInputDialog(null, "Ingrese la cantidad de nombres:");
int limite = Integer.parseInt(pedirTamano);


String[] misNombres = new String[limite];


for (int x = 0; x < limite; x++) {
    misNombres[x] = JOptionPane.showInputDialog(null, "Escriba el nombre:");
    
   
    System.out.println(misNombres[x]);
}
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
      /*  
        String cantidad= JOptionPane.showInputDialog(null,"Ingrese el tamaño del arreglo de nombres");
        int arreglo= Integer.parseInt(cantidad);
        
        String[] datos= new String [arreglo];
       
        for(int i=0; i<arreglo; i++){
            
            datos[i]= JOptionPane.showInputDialog(null, "Ingrese el nombre "+i);
            System.out.println(datos[i]);
        }
*/
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEventoActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed

        //Ejercicio 5. Menú

String seleccion = JOptionPane.showInputDialog(null, 
    "Elegir una opción del menú:\n"
    + "1.- Pollo rostizado\n"
    + "2.- Arepa con mantequilla\n"
    + "3.- Arroz con pollo\n"
    + "4.- Empanadas\n"
    + "5.- Pastelitos");


if (seleccion.equals("1")) {
    JOptionPane.showMessageDialog(null, "Usted seleccionó Pollo rostizado \n¡Gracias por su compra!");
} else if (seleccion.equals("2")) {
    JOptionPane.showMessageDialog(null, "Usted seleccionó Arepa con mantequilla \n¡Gracias por su compra!");
} else if (seleccion.equals("3")) {
    JOptionPane.showMessageDialog(null, "Usted seleccionó Arroz con pollo \n¡Gracias por su compra!");
} else if (seleccion.equals("4")) {
    JOptionPane.showMessageDialog(null, "Usted seleccionó Empanadas \n¡Gracias por su compra!");
} else if (seleccion.equals("5")) {
    JOptionPane.showMessageDialog(null, "Usted seleccionó Pastelitos \n¡Gracias por su compra!");
}
























        
      /*  String menu = JOptionPane.showInputDialog(null, 
    "Elegir una opción del menú:\n"
    + "1.- Pollo rostizado\n"
    + "2.- Arepa con mantequilla\n"
    + "3.- Arroz con pollo\n"
    + "4.- Empanadas\n"
    + "5.- Pastelitos\n");
        
        if(menu.equals("1")){
            JOptionPane.showMessageDialog(null, "Usted seleccionó: Pollo rostizado \n ¡Gracias por su compra!");
        }
        if(menu.equals("2")){
            JOptionPane.showMessageDialog(null, "Usted seleccionó: Arepa con mantequilla \n ¡Gracias por su compra!");
        }
        if(menu.equals("3")){
           JOptionPane.showMessageDialog(null, "Usted seleccionó: Arroz con pollo \n ¡Gracias por su compra!"); 
        }
        if(menu.equals("4")){
           JOptionPane.showMessageDialog(null, "Usted seleccionó: Empanadas \n ¡Gracias por su compra!"); 
        }
        if(menu.equals("5")){
            JOptionPane.showMessageDialog(null, "Usted seleccionó: Pastelitos \n ¡Gracias por su compra!");
        }
*/
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnActivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivarActionPerformed


        //Ejercicio 6. Cual es mayor cual es menor?
        
        
 /*      
String n1 = JOptionPane.showInputDialog(null, "Ingrese el primer número:");
String n2 = JOptionPane.showInputDialog(null, "Ingrese el segundo número:");
String n3 = JOptionPane.showInputDialog(null, "Ingrese el tercer número:");

int a = Integer.parseInt(n1);
int b = Integer.parseInt(n2);
int c = Integer.parseInt(n3);


String resultado;

if (a >= b && a >= c) {
    resultado = "El mayor es el primero: " + a;
} else if (b >= a && b >= c) {
    resultado = "El mayor es el segundo: " + b;
} else {
    resultado = "El mayor es el tercero: " + c;
}


JOptionPane.showMessageDialog(null, "Números ingresados: " + a + ", " + b + ", " + c + "\n" + resultado); 
        
  */      
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        String valor1= JOptionPane.showInputDialog(null,"Ingrese el primer valor");
        int v1= Integer.parseInt(valor1);
        
        String valor2= JOptionPane.showInputDialog(null,"Ingrese el segundo valor");
        int v2= Integer.parseInt(valor2);
        
        String valor3= JOptionPane.showInputDialog(null,"Ingrese el tercer valor");
        int v3= Integer.parseInt(valor3);
        
        int mayor = v1;

if( v2 > mayor){
    mayor= v2;
}
if(v3 > mayor){
    mayor= v3;
}

    JOptionPane.showMessageDialog(null,"Los valores son.. \nPrimer Valor: " + v1 + 
           "\n"+ "Segundo Valor: " +v2+ "\n" +
            "Tercer Valor: " +v3+ "\n" +
            "El número mayor es: " +mayor);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActivarActionPerformed

    private void btnContarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContarActionPerformed

        //Ejercicio 7. Ciclo repetitivo 
 
        
  /*     
String nombre = texto.getText();
int cantidad = Integer.parseInt(repeticion.getText());


String resultado = "";

// Ciclo for estándar (como se enseña en la universidad)
for (int i = 0; i <cantidad; i++) {
    resultado += i + ". " + nombre + "\n";
}


System.out.println(resultado);
texto.setText("");
repeticion.setText("");
texto.requestFocus();
        
   */     
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
       
        
        String nombreIngresado= txtnombre.getText();
        String cantidad= txtcantidaRepetir.getText();
        
        int repeticion= Integer.parseInt(cantidad);
        String resultadorepetitivo= "";
        
        
        for(int i=0; i<repeticion; i++){
            
            resultadorepetitivo = resultadorepetitivo + (i ) + ".- " + nombreIngresado+  "\n";
        }

        System.out.println(resultadorepetitivo);
        
         txtnombre.setText("");
         txtcantidaRepetir.setText("");
         txtnombre.requestFocus();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnContarActionPerformed

    private void botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActionPerformed


 int numer1= Integer.parseInt(numero1.getText());
     int  numer2= Integer.parseInt(numero2.getText());
     int numer3= Integer.parseInt(numero3.getText());
     int calcular= (numer1 + numer2 + numer3 )/3;
     Object[] fila= {numer1, numer2, numer3, calcular};
     modelo.addRow(fila);
     numero1.setText("");
     numero2.setText("");
     numero3.setText("");
     numero1.requestFocus();
     




        // TODO add your handling code here:
    }//GEN-LAST:event_botonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Proyecto_Final4().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaPromedios;
    private javax.swing.JButton boton;
    private javax.swing.JButton btnAccionar;
    private javax.swing.JButton btnActivar;
    private javax.swing.JButton btnContar;
    private javax.swing.JButton btnEvento;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnVerificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mostrar;
    private javax.swing.JTextField numero1;
    private javax.swing.JTextField numero2;
    private javax.swing.JTextField numero3;
    private javax.swing.JTextField txtcantidaRepetir;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField valorNumero;
    // End of variables declaration//GEN-END:variables
}
