/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectodegestioncitas;

/**
 *
 * @author DELL
 */
import javax.swing.table.*;
public class GestionDeCita extends javax.swing.JFrame {
    
  
    DefaultTableModel modelo;
    
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GestionDeCita.class.getName());

    /**
     * Creates new form GestionDeCita
     */
    public GestionDeCita() {
        initComponents();
        
       this.setTitle("Desarrollado por: Yilibeth Ortiz");
       this.setLocationRelativeTo(this);
       this.setResizable(false);
        
    modelo= (DefaultTableModel) tblAgenda.getModel();
      String[] columnas= {"Hora", "Clienta", "Servicio", "Telefono", "Precio"};
      modelo.setColumnIdentifiers(columnas);
      tblAgenda.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txtTelefono = new javax.swing.JPanel();
        btnAgendar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAgenda = new javax.swing.JTable();
        txtCliente = new javax.swing.JTextField();
        txtHora = new javax.swing.JTextField();
        cboServicio = new javax.swing.JComboBox<>();
        txtCelular = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cboHorario = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(204, 255, 255));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTelefono.setBackground(new java.awt.Color(255, 204, 255));
        txtTelefono.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgendar.setText("Agendar");
        btnAgendar.addActionListener(this::btnAgendarActionPerformed);
        txtTelefono.add(btnAgendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        tblAgenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Hora", "Cliente", "Servicio", "Telefono", "Total a Pagar"
            }
        ));
        jScrollPane1.setViewportView(tblAgenda);

        txtTelefono.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 530, -1));
        txtTelefono.add(txtCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 190, -1));
        txtTelefono.add(txtHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 190, -1));

        cboServicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un Servicio", "Manicura Simple", "Sistema de Uñas Acrílicas", "Pedicura Spa", "Corte y Secado de Cabello", "Tinte / Baleyage", "Diseño de Cejas y Pestañas" }));
        txtTelefono.add(cboServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 200, 30));
        txtTelefono.add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 190, -1));
        txtTelefono.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 190, -1));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel1.setText("Hora");
        txtTelefono.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));
        txtTelefono.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel3.setText("Cliente");
        txtTelefono.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel4.setText("Precio");
        txtTelefono.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel5.setText("Celular");
        txtTelefono.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        cboHorario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciones el Horario...", "Mañana(AM)", "Tarde(PM)" }));
        txtTelefono.add(cboHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 22, 170, 30));

        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 480));

        jTabbedPane1.addTab("Agenda Cita", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane1.addTab("tab2", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane1.addTab("tab3", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane1.addTab("tab4", jPanel4);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1070, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendarActionPerformed

String clienta= txtCliente.getText().trim();
String telefono= txtCelular.getText().trim();
String servicio= cboServicio.getSelectedItem().toString();

int hora= Integer.parseInt(txtHora.getText());
String horarioBloque= cboHorario.getSelectedItem().toString();
double precio= Double.parseDouble(txtHora.getText());

if(clienta.isEmpty() || telefono.isEmpty() || servicio.equals("Seleccione un servicio...")){
    
   javax.swing.JOptionPane.showMessageDialog(this, "Error por favor, llene todos los campos");
}else{
    
    String horafinal= "";
    
  if(horarioBloque.equals("Mañana(AM)")){
      horafinal= hora + ":00 AM";
      
  }else if(horarioBloque.equals("Tarde (PM)")){
      horafinal= hora + ":00 PM";
  
  }
    
    System.out.println("Datos listos Cliente: "+ clienta + "-Sevicio"+ servicio);
    Object[] fila= {horafinal, clienta, servicio, telefono, precio + "$"};
    modelo.addRow(fila);
    
    txtHora.setText("");
    txtCliente.setText("");
    txtCelular.setText("");
    txtPrecio.setText("");
    cboServicio.setSelectedIndex(0);
    cboHorario.setSelectedIndex(0);
    
    txtCliente.requestFocus();
    
   
}




       
    }//GEN-LAST:event_btnAgendarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GestionDeCita().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgendar;
    private javax.swing.JComboBox<String> cboHorario;
    private javax.swing.JComboBox<String> cboServicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblAgenda;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JPanel txtTelefono;
    // End of variables declaration//GEN-END:variables
}
