/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DELL
*/
import javax.swing.table.*;
import javax.swing.JOptionPane;
public class Calificar extends javax.swing.JFrame {
    
    
    DefaultTableModel modelo;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Calificar.class.getName());

    public Calificar() {
        initComponents();
        
         this.setTitle("Desarrollado por : ORTIZ");
    this.setLocationRelativeTo(this);    
      this.setResizable(false);

       modelo = (DefaultTableModel) tablaValores.getModel();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNumero = new javax.swing.JTextField();
        btnCalificare = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaValores = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 160, -1));

        btnCalificare.setText("CALIFICAR");
        btnCalificare.addActionListener(this::btnCalificareActionPerformed);
        jPanel1.add(btnCalificare, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        tablaValores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numeros", "Pares", "Impares"
            }
        ));
        jScrollPane4.setViewportView(tablaValores);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 50, 410, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalificareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalificareActionPerformed

if(txtNumero.getText().trim().equals("")){
    JOptionPane.showMessageDialog(this, "Por Favor, introduce un numero");
}else{
    int num= Integer.parseInt(txtNumero.getText());
    
    if(num %2==0){
        
        Object[] filaPar= {num, num, ""};        
        modelo.addRow(filaPar);       
    }else{
        Object[] filaImpar= {num, "", num};
        modelo.addRow(filaImpar);
    }
    txtNumero.setText("");
    txtNumero.requestFocus();
    
}

    }//GEN-LAST:event_btnCalificareActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Calificar().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalificare;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tablaValores;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
